### ISSUE TITLE
GitHub Auth Timeout is too low

### ISSUE THREAD

**Issue by addievo** [MatrixAI/Polykey#588]
### Describe the bug

GitHub auth times out before completion due to timeout being too low

### To Reproduce

1. Try claiming github identity.
2. Wait
3. It aborts

### Expected behavior

Should not abort unexpectedly.

### Platform (please complete the following information)
 - Version: CLI

**Comment by CMCDragonkai** [comment]
This will require the new RPC release. @tegefaulkes what's the new version for this?

**Comment by tegefaulkes** [comment]
New release is `@matrixai/rpc` `0.2.5`

**Comment by tegefaulkes** [comment]
@CMCDragonkai found that the identities claim times out to quickly. This was fixed right? I'm going to re-open this issue until it's confirmed again.

It's only considered complete if the CLI command `identities claim` can be completed without feeling rushed.

**Comment by CMCDragonkai** [comment]
I think this was confused, the #589 certainly didn't fix it. https://github.com/MatrixAI/Polykey-CLI/pull/49 was closed and #625 is still part of solving this.

**Comment by amydevs** [comment]
This regression has been fixed. The changes to the MDNS timeout, where the a client's shorter timeout would override that of a server had broken it. I have set the timeout to be equal on the client to be 120000ms (2 minutes). Commit: https://github.com/MatrixAI/Polykey-CLI/commit/35d2cf147f59d5da18f46dddd6c9e3416f44d400
